name: turb
channels:
  - conda-forge
  - bioconda
dependencies:
  - requests=2.31.0
  - pandas=2.1.4
  - certifi=2023.11.17
  - snakemake=8.0.1
  - graphviz=9.0.0
  - r-base=4.3.2
  - r-tidyverse=2.0.0
  - r-terra=1.7_65
  - r-targets=1.4.0
  - r-future=1.33.1
  - r-batchtools=0.9.17
  - r-future.callr=0.8.2
  - r-usethis=2.2.2
  - r-visnetwork=2.1.2